spring:
  freemarker:
    suffix: .html
  #devtools:
   # livereload.enabled: true
    #restart.exclude: static/**,public/**
    #reload.trigger-file: .html
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        type: trace
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/online_seva?verifyServerCertificate=false&useSSL=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

---
spring:
  profiles: postgres
  freemarker:
    suffix: .html
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.apache.http: DEBUG

---
spring:
  profiles: errorlogs
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
  messages:
    basename: validation
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error
management:
  endpoints:
    web:
      exposure:
        include: "*"